### PR TITLE
Fix #368: allow specification of arbitrary rsiviz configuration

### LINKED ISSUE #368: allow configuration of all rsiviz values
RSIVIZ_UTIL_DET_CAL_F, RSIVIZ_UTIL_ANALYSIS_D, etc.

### PR DESCRIPTION
**Pull request by e-carlin**

### CODE REVIEW

**Comment by e-carlin** [comment]
@gurhar1133 ping. There is a PR I'd like to open that needs these changes so please review as soon as you have time.

**Review by gurhar1133 — APPROVED** [review]
Looks good.

One question. Once the exclude_re is passed to pkconfig.to_environ and we are checking keys for the exclude_re, what do those keys represent?

**Comment by e-carlin** [comment]
Thanks

Those keys represent the names of the environment variables (ex PYKERN_PKCONFIG_CHANNEL). So, we want to exclude certain values that contain sensistive data that doesn't need to be available in the environment (ex a secret that no service reads from the env).

```python
from pykern import pkconfig
from pykern.pkcollections import PKDict
from pykern.pkdebug import pkdp

for e in "", r"some_secret":
    pkdp(pkconfig.to_environ(["*"], values=PKDict(foo=1, some_secret=2), exclude_re=e))
```

**Comment by gurhar1133** [comment]
> Thanks
> 
> Those keys represent the names of the environment variables (ex PYKERN_PKCONFIG_CHANNEL). So, we want to exclude certain values that contain sensistive data that doesn't need to be available in the environment (ex a secret that no service reads from the env).
> 
> ```python
> from pykern import pkconfig
> from pykern.pkcollections import PKDict
> from pykern.pkdebug import pkdp
> 
> for e in "", r"some_secret":
>     pkdp(pkconfig.to_environ(["*"], values=PKDict(foo=1, some_secret=2), exclude_re=e))
> ```

Thank you 👍

**Pull request merged**
