### PR TITLE
Fix #322 use Cloudflare modern for PCI DSS, ssl labs strong

### LINKED ISSUE #322: Update SSL ciphers to be PCI compatible

### PR DESCRIPTION
**Pull request by schellj**
Sorry for the back-and-forth on this. The cipher name format from #321 was correct after all for the version of openssl that we're using, but appears to have changed in a later version (for which I was looking at the man page). I checked the `nginx.conf` with `nginx -t`.

This PR is contains the list of ciphers from #321 minus the ones that SSL labs considers weak (`ECDHE-ECDSA-AES128-SHA256` / `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256`, `ECDHE-RSA-AES128-SHA256` / `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`, `ECDHE-ECDSA-AES256-SHA384` / `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384`, `ECDHE-RSA-AES256-SHA384` / `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384`).

### CODE REVIEW

**Comment by robnagler** [comment]
@e-carlin I'm assigning to you, because I am not available.

**Review by e-carlin — APPROVED** [review]
LGTM. Tested on a local rsconf install.

**Comment by e-carlin** [comment]
Deployed to sirepo alpha and it worked there.

**Comment by schellj** [comment]
Thanks. Looks like sirepo alpha is now using the expected ciphers. On the flip-side, it should be noted that with this restricted set of ciphers, some older browsers won't be able to complete the handshake:
image
image
The above browsers would have used the `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256` cipher, which was removed in this PR.

**Comment by moellep** [comment]
@e-carlin this is ready for production today. I'm not sure on the process to release this - could you let me know the steps?

**Comment by e-carlin** [comment]
@moellep nothing needs to be done. I actually released it to prod yesterday because I had to update jupyter which pulled in these changes.

**Comment by schellj** [comment]
@e-carlin when you say you released this to prod, what hosts should have the update? The ciphers on sirepo.com don't seem to be updated (https://www.ssllabs.com/ssltest/analyze.html?d=sirepo.com).

**Comment by e-carlin** [comment]
sirepo.com is the http site which does a redirect to the https site. This happens on atl2i. 

```bash
~$ dig +short -x $(dig +short sirepo.com)
atl2i.bivio.biz.
~$ openssl s_client -connect sirepo.com:443 -cipher ECDHE-RSA-AES128-SHA256
CONNECTED(00000003)
<snip>
```

When I say "released to prod" I mean the https site (https://www.sirepo.com):
```bash
~$ dig +short -x $(dig +short www.sirepo.com)
bkf4i.bivio.biz.
~$ openssl s_client -connect www.sirepo.com:443 -cipher ECDHE-RSA-AES128-SHA256
CONNECTED(00000003)
004E3978E37F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1605:SSL alert number 40
```

Should changes be deployed to atl2i as well? I've never done a deploy to that server so I may want to wait until Rob is back  if we need to deploy there...

**Comment by schellj** [comment]
Thanks for the information. I didn't realize there was a redirect from sirepo.com to www.sirepo.com (partially due to the fact that Chrome hides the `www` in the URL bar now days) and that I needed to specifically run the ssllabs test on the latter.

**Comment by robnagler** [comment]
I updated to have a bit more info: https://github.com/biviosoftware/devops/blob/master/wiki/Systems.md

**Pull request merged**
