### PR TITLE
Fix #303 static file support for sirepo tornado

### LINKED ISSUE #303: Generate static files before server starts up
Something like:

```bash
install -d -u vagrant /var/www/sirepo.new
/srv/sirepo/start sirepo static_files gen /var/www/sirepo -- needs to mount /var/www/sirepo.new
find /var/www/sirepo.new -type d -print0 | xargs -0 chmod 711
find /var/www/sirepo.new -type f -print0 | xargs chmod 444
mv /var/www/sirepo /var/sirepo.old
mv /var/www/sirepo.new var/sirepo
```

Perhaps this could only happen when there's a new docker image, that is, there could be a new trigger when the docker image changes that runs this command.

Prerequisite: https://github.com/radiasoft/sirepo/pull/5664

### PR DESCRIPTION
**Pull request by robnagler**
@e-carlin we should wait to merge until #304 is merged

- Moved systemd scripts to prepare() from enable(), because static_files_gen needs to call /srv/sirepo/start
- rsconf_service_docker_pull has a static_files_gen hook to callback to the component (e.g. sirepo)
- systemd service_exec & cmd were confusing. consistently named timer_exec and docker_exec
- nginx serves files from /srv/www. /usr/share/nginx/html shouldn't be modified, and apache uses /var/www

### CODE REVIEW

**Comment by robnagler** [comment]
@e-carlin ping

**Review by e-carlin — APPROVED** [review]
LGTM. 

Not sure if this is related or not but when trying to run a sim in Sirepo using this rsconf config I'm seeing 


```
Apr 21 21:13:17 v4.radia.run sirepo_job_supervisor[15264]: AssertionError: ('docker', '--host=tcp://v4.radia.run:2376', '--tlsverify', '--tlscacert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cacert.pem', '--tlscert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cert.pem', '--tlskey=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/key.pem', 'run', '--attach=stdin', '--init', '--interactive', '--name=srj-s-uTwtw1AY', '--network=host', '--rm', '--ulimit=core=0', '--ulimit=nofile=1024', '--user=1000', '--cpus=1', '--memory=1g', '--volume=/srv/sirepo/db/user/uTwtw1AY:/srv/sirepo/db/user/uTwtw1AY', 'v3.radia.run:5000/radiasoft/sirepo:dev', '/bin/bash', '-l'): failed: exit=125 output=docker: Cannot connect to the Docker daemon at tcp://v4.radia.run:2376. Is the docker daemon running?.
```

**Comment by robnagler** [comment]
> Not sure if this is related or not but when trying to run a sim in Sirepo using this rsconf config I'm seeing

check the time on v3 and v4 machines.

**Comment by e-carlin** [comment]
The time is the same

**Comment by robnagler** [comment]
We debugged this. The files in v3 download were out of date (https://github.com/radiasoft/rsconf/issues/315) and the provisioner was therefore not editing out v4.radia.run from /etc/hosts.

**Pull request merged**
